#Even Fibonacci numbers
#Problem 2
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#! python3

a = 1
b = 2
fib_list = [1, 2]
total = 0
even_total = 2

while total < 4000000:
    total = a + b
    if total > 4000000:
        break
    fib_list.append(total)
    a = b
    b = total
    if total % 2 == 0:
        even_total += total

print(fib_list)
print(even_total)
    
    
