#Triangular, pentagonal, and hexagonal
#Problem 45
#Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

#Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
#Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
#Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
#It can be verified that T285 = P165 = H143 = 40755.

#Find the next triangle number that is also pentagonal and hexagonal.

tria = {0}
pent = {0}
hexa = {0}

for num in range(1, 100000):
    tria.add(int(num * (num + 1) / 2))
    pent.add(int(num * (3 * num - 1) / 2))
    hexa.add(int(num * (2 * num - 1)))

interset = {0, 1}

interset = tria.intersection(pent)
interset = interset.intersection(hexa)
interset -= {0, 1}

print(interset)
             
